# TODO use env var for paths
# TODO use default block

:default: &default
  :pull: |-
    cd %{building_workspace_path} &&
    git clone --depth=1 https://github.com/%{github_repo_path} ./app_content &&
    mv ./app_content/config ./app/ &&
    mv ./app_content/story ./app/ &&
    mv ./app_content/resources ./app/ &&
    rm -rf ./app_content

:development:
  <<: *default
  :build: |-
    bash -lc "
    source $NVM_DIR/nvm.sh &&
    nvm use node &&
    cd %{building_workspace_path} &&
    gulp build"
  :compress: |-
    cd %{building_workspace_path}/dist &&
    zip -r %{archive_file_path} ./*

:production:
  <<: *default
  :build: |-
    cd %{building_workspace_path} &&
    gulp build
  :compress: |-
    cd %{building_workspace_path}/dist &&
    zip -r -9 %{archive_file_path} ./*
