# TODO use env var for paths
# TODO use default block

:default: &default
  :pull: |-
    cd %{building_workspace_path} &&
    git clone --depth=1 https://github.com/%{github_repo_path} ./app_content &&
    mv ./app_content/* ./app/

:development:
  <<: *default
  :build: |-
    bash -lc "
    source $NVM_DIR/nvm.sh &&
    nvm use node &&
    source $HOME/.rvm/scripts/rvm &&
    rvm use default &&
    cd %{building_workspace_path} &&
    gulp build"
  :compress: |-
    cd %{building_workspace_path}/dist &&
    zip -r %{archive_file_path} ./*

:production:
  <<: *default
  :build: |-
    bash -lc "
    cd %{building_workspace_path} &&
    gulp build"
  :compress: |-
    cd %{building_workspace_path}/dist &&
    zip -r -9 %{archive_file_path} ./*
