# TODO use env var for paths
# TODO use default block

:default: &default
  :pull: |-
    cd %{building_workspace_path} &&
    git clone --depth=1 %{git_repo_path} ./app_content &&
    mv ./app_content/config ./app/ &&
    mv ./app_content/story ./app/ &&
    mv ./app_content/resources ./app/ &&
    rm -rf ./app_content

:development:
  <<: *default
  :build_web: |-
    bash -lc "
    source $NVM_DIR/nvm.sh &&
    nvm use node &&
    cd %{building_workspace_path} &&
    gulp build"
  :build_android: |-
    bash -lc "
    source $NVM_DIR/nvm.sh &&
    nvm use node &&
    cd %{building_workspace_path} &&
    cordova create cordova_workspace %{app_id} %{app_name} &&
    cd cordova_workspace &&
    cordova platform add android &&
    rm -rf ./www &&
    mv %{built_dist_path} ./www &&
    cordova build android"
  :compress: |-
    cd %{building_workspace_path}/dist &&
    zip -r %{archive_file_path} ./*

:production:
  <<: *default
  :build_web: |-
    bash -lc "
    source $HOME/.rvm/scripts/rvm &&
    cd %{building_workspace_path} &&
    gulp build"
  :build_android: |-
    bash -lc "
    cd %{building_workspace_path} &&
    cordova create cordova_workspace %{app_id} %{app_name} &&
    cd cordova_workspace &&
    cordova platform add android &&
    rm -rf ./www &&
    mv %{built_dist_path} ./www &&
    cordova build android"
  :compress: |-
    cd %{building_workspace_path}/dist &&
    zip -r -9 %{archive_file_path} ./*
